export const GET_ABOUT_NAMES_JSON_DATA = "GET_ABOUT_NAMES_JSON_DATA";
export const GET_ABOUT_USER_JSON_DATA = "GET_ABOUT_USER_JSON_DATA";

export const LOADER_START = "LOADER_START";
export const LOADER_STOP = "LOADER_STOP";

export const MODAL_LOADER_START = "MODAL_LOADER_START";
export const MODAL_LOADER_STOP = "MODAL_LOADER_STOP";
